# Generated by Django 3.1.4 on 2021-07-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('location', models.CharField(max_length=128)),
                ('init_date', models.DateField()),
                ('init_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('is_public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
