# Generated by Django 3.1.4 on 2021-08-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20210810_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='url_plan_picture',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(null=True),
        ),
    ]
