# Generated by Django 3.1.4 on 2021-09-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20210831_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='english_description',
            field=models.CharField(default='pending translation', max_length=1024),
        ),
        migrations.AddField(
            model_name='plan',
            name='english_title',
            field=models.CharField(default='pending translation', max_length=256),
        ),
    ]
