# Generated by Django 3.1.4 on 2021-09-03 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_username', models.CharField(default='No Username', max_length=128)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('biography', models.CharField(default='No biography', max_length=1024)),
                ('residence', models.CharField(default='No residence', max_length=256)),
                ('url_profile_picture', models.CharField(default='No profile Picture', max_length=512)),
                ('friends', models.ManyToManyField(blank=True, to='userprofiles.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
