# Generated by Django 3.1.4 on 2021-08-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.CharField(default='Test biography', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='userprofiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='residence',
            field=models.CharField(default='Test Residence', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url_profile_picture',
            field=models.CharField(default='Test url', max_length=512),
            preserve_default=False,
        ),
    ]
