# Generated by Django 3.1.4 on 2021-08-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20210814_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.CharField(default='No biography', max_length=1024),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='residence',
            field=models.CharField(default='No residence', max_length=256),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='url_profile_picture',
            field=models.CharField(default='No profile Picture', max_length=512),
        ),
    ]
