# Generated by Django 3.1.4 on 2021-08-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20210814_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_username',
            field=models.CharField(default='No Username', max_length=128),
        ),
    ]
