# Generated by Django 3.1.4 on 2021-08-14 15:41

from django.db import migrations, models
import django.db.models.deletion
import friendship.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofiles', '0003_auto_20210814_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('request_status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default=friendship.models.FriendRequestStatus['PENDING'], max_length=64)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='userprofiles.userprofile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='userprofiles.userprofile')),
            ],
        ),
    ]
