# Generated by Django 3.1.4 on 2021-09-03 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lemma', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('corresponding_plans', models.ManyToManyField(to='plans.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance', models.FloatField(default=-1.0)),
                ('plan1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan1', to='plans.plan')),
                ('plan2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan2', to='plans.plan')),
            ],
        ),
    ]
